apiVersion: v1
kind: ConfigMap
metadata:
  name: instana-agent
  namespace: placeholder
  ownerReferences:
    - apiVersion: apps/v1
      kind: InstanaAgent
      name: placeholder
      uid: placeholder
data:
  configuration.yaml: placeholder
